security:
    basic:
      enabled: false


management:
    security:
      enabled: false

logging:
   level:
      io:
       pivotal: INFO

abc:
   displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote

